### ISSUE TITLE
CEDAR contacts broken

### ISSUE THREAD

**Issue by cebriggs7135** [metadatacenter/cedar-artifact-viewer#12]
I am trying to get info on your spreadsheet tools (if they even exist yet) but none of the contact routes listed here work:
https://more.metadatacenter.org/tools-training/support

The FILL OUT FORM button is broken and an email I sent to 

cedar-support@metadatacenter.org

bounced back saying:
*You are not allowed to post to this mailing list, and your message has
been automatically rejected.  If you think that your messages are
being rejected in error, contact the mailing list owner at
cedar-users-owner@lists.stanford.edu.*

**Comment by graybeal** [comment]
Thanks for catching these Chris, and very sorry for the issues.

The bounce-back issue with the mail list has been fixed, messages will now be moderated as originally intended.

The Fill Out Form no longer works as a fill out form, so the link pointing to that has been removed and the text at that page changed to be simple instructions for emailing us.
